### ISSUE TITLE
Error: Metadata.json file can't be read: run this from a directory containing a metadata file.

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#22]
Following [`README.md`](https://github.com/WebPlatformForEmbedded/Lightning-SDK)  and running `npm run release-web` I get this error:
```
Error: Metadata.json file can't be read: run this from a directory containing a metadata file.
    at ReadFileContext.callback (C:\Users\matti\OneDrive\Documenti\projects\Lightning-Gennaio\Lightning-SDK\node_modules\wpe-lightning-sdk\scripts\release-web.js:34:31)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! your-app@1.0.0 release-web: `node ./node_modules/wpe-lightning-sdk/scripts/release-web.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the your-app@1.0.0 release-web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\matti\AppData\Roaming\npm-cache\_logs\2020-01-08T13_44_01_689Z-debug.log
```
Here's my `package.json`:
```
{
    "author": "Metrological",
    "name": "your-app",
    "version": "1.0.0",
    "dependencies": {
        "wpe-lightning-sdk": "git+https://github.com/WebPlatformForEmbedded/Lightning-SDK.git"
    },
    "scripts": {
        "release-web": "node ./node_modules/wpe-lightning-sdk/scripts/release-web.js",
        "release-mpkg": "node ./node_modules/wpe-lightning-sdk/scripts/release-mpkg.js",
        "upload-app": "node ./node_modules/wpe-lightning-sdk/scripts/upload-app-metrological.js"
    }
}
```

**Comment by michielvandergeest** [comment]
It seems like your project doesn't contain  metadata.json file as described here: 

https://github.com/WebPlatformForEmbedded/Lightning-SDK#metrological-package

example metadata.json:

```
{
  "name": "MyApp",
  "identifier": "com.acme.app.myapp",
  "version": "1.0.0",
  "icon": "./static/icon.png"
}
```
